In [1]:
import pandas as pd

In [8]:
go_groups = pd.read_csv('/vault/transfer/passala/Generated_Tables/Reference_tables/all_annotated_go_groups.csv', encoding='cp1252', index_col=0)
go_groups

,Avg FC,Avg EGAD,Name,EGAD Counts,Annotation,Notes
GO:0000003,0.740324,0.634227,reproduction,10,NaN,NaN
GO:0000018,0.766573,0.798689,regulation of DNA recombination,8,NaN,NaN
GO:0000027,0.923946,0.869159,ribosomal large subunit assembly,9,Ribosomal,NaN
GO:0000028,0.951180,0.875073,ribosomal small subunit assembly,9,Ribosomal,NaN
GO:0000030,0.714718,0.642678,mannosyltransferase activity,8,NaN,Critical function in eukaryotes
...,...,...,...,...,...,...
GO:2001020,0.821085,0.761272,regulation of response to DNA damage stimulus,9,NaN,NaN
GO:2001070,0.720227,0.869219,starch binding,7,NaN,NaN
GO:2001141,0.722697,0.673483,regulation of RNA biosynthetic process,6,NaN,NaN
GO:2001251,0.778751,0.805120,negative regulation of chromosome organization,9,NaN,NaN
GO:2001252,0.821120,0.790655,positive regulation of chromosome organization,8,NaN,NaN

In [7]:
go_groups[go_groups['Annotation'] == 'Hormonal'].sort_values('Avg FC')

,Avg FC,Avg EGAD,Name,EGAD Counts,Annotation,Notes
GO:0009686,0.565007,0.739009,gibberellin biosynthetic process,5,Hormonal,NaN
GO:0080032,0.566563,0.775655,methyl jasmonate esterase activity,4,Hormonal,NaN
GO:0080031,0.566563,0.775655,methyl salicylate esterase activity,4,Hormonal,NaN
GO:0080030,0.570538,0.698227,methyl indole-3-acetate esterase activity,5,Hormonal,NaN
GO:0010268,0.571501,0.747605,brassinosteroid homeostasis,8,Hormonal,NaN
GO:0009691,0.576860,0.688781,cytokinin biosynthetic process,6,Hormonal,NaN
GO:0009685,0.583506,0.751984,gibberellin metabolic process,6,Hormonal,NaN
GO:0009690,0.583757,0.662429,cytokinin metabolic process,7,Hormonal,NaN
GO:0035672,0.586452,0.792224,oligopeptide transmembrane transport,9,Hormonal,NaN
GO:0035673,0.586452,0.791121,oligopeptide transmembrane transporter activity,9,Hormonal,NaN
GO:1900750,0.587250,0.768058,oligopeptide binding,6,Hormonal,NaN
GO:0006857,0.587271,0.786661,oligopeptide transport,10,Hormonal,NaN
GO:0015333,0.588562,0.804464,peptide:proton symporter activity,9,Hormonal,NaN
GO:0009696,0.594588,0.735849,salicylic acid metabolic process,4,Hormonal,NaN
GO:0016131,0.606155,0.712313,brassinosteroid metabolic process,8,Hormonal,NaN
GO:0042447,0.611815,0.710880,hormone catabolic process,4,Hormonal,NaN
GO:0016132,0.612878,0.664608,brassinosteroid biosynthetic process,8,Hormonal,NaN
GO:0120178,0.612878,0.666248,steroid hormone biosynthetic process,8,Hormonal,NaN
GO:0042445,0.613010,0.701089,hormone metabolic process,10,Hormonal,NaN
GO:0042446,0.615780,0.679233,hormone biosynthetic process,10,Hormonal,NaN
GO:0009694,0.616617,0.791934,jasmonic acid metabolic process,9,Hormonal,NaN
GO:0005992,0.630766,0.775610,trehalose biosynthetic process,8,Hormonal,trehalose hormone?
GO:0005991,0.634146,0.780447,trehalose metabolic process,8,Hormonal,trehalose hormone?
GO:0009850,0.634481,0.694455,auxin metabolic process,8,Hormonal,NaN
GO:0010817,0.643127,0.667887,regulation of hormone levels,10,Hormonal,NaN
GO:0010329,0.649334,0.785633,auxin efflux transmembrane transporter activity,5,Hormonal,NaN
GO:0010315,0.651178,0.789997,auxin efflux,5,Hormonal,NaN
GO:0080161,0.651312,0.805902,auxin transmembrane transporter activity,5,Hormonal,NaN
GO:0009695,0.655312,0.875871,jasmonic acid biosynthetic process,4,Hormonal,NaN
GO:0010427,0.663959,0.810734,abscisic acid binding,8,Hormonal,NaN
GO:0009914,0.670234,0.701539,hormone transport,7,Hormonal,NaN
GO:0060918,0.672577,0.703878,auxin transport,7,Hormonal,NaN
GO:0009926,0.673008,0.723572,auxin polar transport,7,Hormonal,NaN
GO:0010252,0.673135,0.657576,auxin homeostasis,6,Hormonal,NaN
GO:0042562,0.682148,0.756386,hormone binding,10,Hormonal,NaN
GO:0009755,0.693203,0.690625,hormone-mediated signaling pathway,10,Hormonal,NaN
GO:0080142,0.713027,0.817550,regulation of salicylic acid biosynthetic process,6,Hormonal,NaN
GO:0046885,0.717160,0.782140,regulation of hormone biosynthetic process,8,Hormonal,NaN
GO:0032350,0.717443,0.788698,regulation of hormone metabolic process,8,Hormonal,NaN
GO:0010337,0.717877,0.820366,regulation of salicylic acid metabolic process,6,Hormonal,NaN
GO:0043434,0.723464,0.787263,response to peptide hormone,4,Hormonal,NaN
GO:0048545,0.739494,0.611064,response to steroid hormone,9,Hormonal,NaN